global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'agent_ui'
    metrics_path: /metrics
    static_configs:
      - targets: ['agent_ui:80']

  - job_name: 'mail_assistant'
    metrics_path: /metrics
    static_configs:
      - targets: ['mail_assistant:8002']
