FROM nginx:alpine

RUN apk add --no-cache apache2-utils bash

COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

EXPOSE 9181

ENTRYPOINT ["/entrypoint.sh"]